version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - DB_URI=mongodb://localhost:27017
    depends_on:
      - mongo
    network_mode: "host"

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    network_mode: "host"

volumes:
  mongo_data:
